### ISSUE TITLE
parameters values

### ISSUE THREAD

**Issue by almogmor** [Adamantios/Atari-Skiing-RL#1]
Hi, 
I'm trying to run the script but I don't get similar result as you show under "trained performance"

Can you please speciffy the exect parameters and their values that you use in order to get this agent ?

**Comment by Adamantios** [comment]
Hi,
Do you mean the gif animation?
After searching for the optimal hyperparameters, I trained the agent using the following arguments:
`skiing.py --replay_memory 5000 --agent_history 5 --downsample 2 --frame_skipping 3 --fit_frequency 3 --final_epsilon 0.1 --decay 1e-5 --observe 5e4 --batch 64  --learning_rate 0.95`
The `--no_render` argument was also used in order to train the model fast and not have to wait for the graphics to render.
After the training had finished, I used the trained agent (`--agent` argument) and ran the script only for one episode, using the argument `--record` in order to record it and `--recording_name_prefix` in order to name the file as `trained-agent`.
Finally, I recorded the script for an untrained agent without random steps (`--no_operation` set to 0) and named the recorded file as `untrained_agent`.
In order to generate the comparison gif, I used a video editing program to sync the two gifs duration and render them side by side.

I just noticed that I have not updated the Readme file to contain the recording arguments, though you can use the `--help` argument which will show the most recent help description.

**Comment by almogmor** [comment]
Hello again,
So we're trying to run the script with the same parameters as above.
But after 2500 episodes of training we still haven't succeeded to get the
same result.

Can you please tell me how many episodes did you train to get the published
results?

Thanks ahead,
Almog.


‫בתאריך יום ה׳, 8 באוק׳ 2020 ב-14:52 מאת ‪Adamantios Zaras‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by Adamantios** [comment]
Hello, the agent was trained for 10,000 episodes in order to get the demonstrated results.

**Comment by almogmor** [comment]
Thanks for the quick response!

‫בתאריך יום ה׳, 29 באוק׳ 2020 ב-22:40 מאת ‪Adamantios Zaras‬‏ <‪
notifications@github.com‬‏>:‬
